### get Places using kakaoApi
GET http://localhost:8000/plrecipe-place/findBasePlace/스타필드

### getPlace
GET http://localhost:8000/plrecipe-place/find/5

### getPlaceAll
GET http://localhost:8000/plrecipe-place/find

### searchPlaceByFilter
POST http://localhost:8000/plrecipe-place/searchPlace
Content-Type: application/json

{
  "name":"붕어",
  "region": null,
  "category": null,
  "star": null

}

### selectStarByPlace
GET http://localhost:8080/star/3

### selectStarByMember
GET http://localhost:8000/plrecipe-place/star/member/5

### selectCoursePlaceByCourseId
GET http://localhost:8000/plrecipe-place/course/findInfo/5

### selectCourseByMember
GET http://localhost:8000/plrecipe-place/course/findUserId/3

### getPlacesByCourseId
GET http://localhost:8000/plrecipe-place/course/findPlaces/1




