### PUT regist Member
POST localhost:8000/plrecipe-member/register
content-Type: application/json

{
  "memberEmail": "babypanda@gmail.com",
  "password": "fub",
  "memberName": "김복보",
  "memberNickname": "김복보",
  "memberNumber": "010-5264-8146",
  "memberGrade": "ROLL_MEMBER",
  "memberStatus": "Y"
}

### Post Login
POST localhost:8000/plrecipe-member/login
content-Type: application/json

{
  "memberEmail": "chosoobn37@gmail.com",
  "password": "soobin"
}

### PATCH modify Member
PATCH localhost:8000/plrecipe-member/modify/4
Content-Type: application/json

{
  "memberEmail": "chosoobn37@gmail.com",
  "password": "soobin",
  "memberName": "조수빈",
  "memberNickname": "조먹밥",
  "memberNumber": "010-3925-6406"
}

### PATCH withdraw Member
PATCH localhost:8000/plrecipe-member/withdraw/33
Content-Type: application/json

{
  "memberStatus": "N"
}

### PUT insert Follow
POST localhost:8000/plrecipe-member/new
content-Type: application/json

{
  "userFollow": 27,
  "userFollower": 5
}

### DELETE delete Follow
DELETE localhost:8000/plrecipe-member/unfollow/25
content-Type: application/json



