### GET request members
GET localhost:8000/plrecipe-member/members

### GET request memberById
GET localhost:8000/plrecipe-member/searchMember/1

### PUT regist Member
POST localhost:8000/plrecipe-member/regist
content-Type: application/json

{
  "memberEmail": "passtest@naver.com",
  "password": "000307hello",
  "memberName": "홍길동",
  "memberNickname": "kim",
  "memberNumber": "010-1812-4521",
  "memberGrade": "ROLL_MEMBER",
  "memberStatus": "Y"
}

### PATCH modify Member
PATCH localhost:8000/plrecipe-member/modify/35
Content-Type: application/json

{
  "memberEmail": "hellotes@naver.com",
  "password": "newPass01",
  "memberName": "제갈바오",
  "memberNickname": "푸야똥",
  "memberNumber": "010-0307-0307"
}

### PATCH withdraw Member
PATCH localhost:8000/plrecipe-member/withdraw/36
Content-Type: application/json

{
  "memberStatus": "N"
}

### GET request followById
GET localhost:8000/plrecipe-member/searchFollow/15

### GET request memberWhoFollowsMe
GET localhost:8000/plrecipe-member/follower/1

### GET request memberWhoIFollow
GET localhost:8000/plrecipe-member/following/5

### PUT insert Follow
POST localhost:8000/plrecipe-member/new
content-Type: application/json

{
  "userFollow": 27,
  "userFollower": 5
}

### DELETE delete Follow
DELETE localhost:8000/plrecipe-member/unfollow/34
content-Type: application/json



