### GET request posts
GET localhost:8080/main/posts

### GET request memberPosts
GET localhost:8080/main/posts/email/1

### GET request postsByStatus
GET localhost:8080/main/posts/status/Y

### GET request postsByMemberCounts
GET localhost:8080/main/posts/memberCounts/TWO

### GET request HashtagsByPostId
GET localhost:8080/main/posts/hashtag/1

### GET request LikesByPostId
GET localhost:8080/main/posts/likes/1

### PUT modifyPost
PUT localhost:8080/main/modify/1
Content-Type: application/json

{
  "postTitle": "수정될까",
  "postIsPublic": "Y",
  "memberCount": "TWO"
}

### GET modified post
GET localhost:8080/main/post/1

