### GET request posts
GET localhost:8080/post/posts

### GET request memberPosts
GET localhost:8080/post/posts/email/1

### GET request postsByStatus
GET localhost:8080/post/posts/status/Y

### GET request postsByMemberCounts
GET localhost:8080/post/posts/memberCounts/TWO

### GET request HashtagsByPostId
GET localhost:8080/post/posts/hashtag/1

### GET request LikesByPostId
GET localhost:8080/post/posts/likes/1

### POST regist Post
POST localhost:8080/post/regist
Content-Type: application/json

{
  "postTitle": "시간도 추가가 될까요 제발",
  "postContent": "제발요 해주세요",
  "postDate": "current_time",
  "memberId": 2,
  "courseId": 3,
  "isPostPublic": "N",
  "memberCount": "ONE"
}

### POST regist Hashtag
POST localhost:8080/post/regist/hashtag
Content-Type: application/json

{
  "hashtagTitle": "해시태그 추가 테스트"
}

### POST regist PostHashtag
POST localhost:8080/post/regist/post_hashtag
Content-Type: application/json

{
  "hashtagId": 1,
  "postId": 10
}

### POST regist PostHashtag

### PATCH modify Post
PATCH localhost:8080/post/modify/1
Content-Type: application/json

{
  "postTitle": "게시글 제목 수정 테스트??",
  "postContent": "게시글 내용 수정 테스트??",
  "courseId": 2,
  "isPostPublic": "Y",
  "memberCount": "TWO"
}

### PATCH delete Post
PATCH localhost:8080/post/delete/10
Content-Type: application/json

{
  "postDeleteDate": "current_date"
}

### GET delete post_hashtag
DELETE localhost:8080/post/hashtag/delete/15

### POST regist post_like
POST localhost:8080/post/like
Content-Type: application/json

{
  "memberId": "21",
  "postId": "10"
}