### POST regist Hashtag
POST localhost:8000/plrecipe-post/regist/hashtag
Content-Type: application/json

{
  "hashtagTitle": "해시태그 추가 테스트15"
}


### PATCH modify Post
PATCH localhost:8888/plrecipe-post/modify/5
Content-Type: application/json

{
  "postTitle": "친구가 없는 당신 냄새나지만 내가 도와주지",
  "postContent": "학교교육 및 평생교육을 포함한 교육제도와 그 운영, 교육재정 및 교원의 지위에 관한 기본적인 사항은 법률로 정한다. 대통령·국무총리·국무위원·행정각부의 장·헌법재판소 재판관·법관·중앙선거관리위원회 위원·감사원장·감사위원 기타 법률이 정한 공무원이 그 직무집행에 있어서 헌법이나 법률을 위배한 때에는 국회는 탄핵의 소추를 의결할 수 있다.",
  "courseId": 2,
  "isPostPublic": "Y",
  "memberCount": "TWO"
}

### PATCH delete Post
PATCH localhost:8000/plrecipe-post/delete/10
Content-Type: application/json

{
  "postDeleteDate": "current_date"
}

### GET delete post_hashtag
DELETE localhost:8000/plrecipe-post/hashtag/delete/26

### POST regist post_like
POST localhost:8000/plrecipe-post/like
Content-Type: application/json

{
  "memberId": "23",
  "postId": "9"
}

### POST test
POST localhost:8000/plrecipe-post/regist_both
Content-Type: application/json

{
  "post":{
    "postTitle": "게시글 제목 추가 테스트",
    "postContent": "게시글 내용 추가 테스트",
    "courseId": 4,
    "memberId": 13,
    "isPostPublic": "Y",
    "memberCount": "TWO",
    "postDate": "123"
  },
  "hashtagId": [1, 2, 3, 4, 5]
}
