### PUT regist Group
POST localhost:8000/plrecipe-group/regist
content-Type: application/json

{
  "groupName": "아우디 지렸다",
  "isGroupPublic": "Y",
  "groupComment": "아우디로만 이동한다 맛집으로!",
  "groupStatus": "Y"
}

### PUT modify Group
PATCH localhost:8000/plrecipe-group/modify/1
content-Type: application/json

{
  "groupName": "푸바오 바보",
  "isGroupPublic": "N",
  "groupComment": "푸바오 똥!!"
}

### PUT delete Group
PATCH localhost:8000/plrecipe-group/delete/1
content-Type: application/json

{
  "groupStatus": "N"
}

### DELETE withdrawal Group
DELETE localhost:8000/plrecipe-group/withdrawal/2
content-Type:application/json


### POST invited Group
POST localhost:8000/plrecipe-group/invite/1/15
content-Type: application/json

### POST invite Accept
POST  localhost:8000/plrecipe-group/accept-invitation/1/10
content-Type: application/json